/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Goji
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public MenuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBody = new javax.swing.JPanel();
        PanelMenu = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnProject = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        IndicatorProject = new javax.swing.JPanel();
        btnService = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        IndicatorService = new javax.swing.JPanel();
        btnProduct = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        IndicatorProduct = new javax.swing.JPanel();
        btnCommunity = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        IndicatorCommunity = new javax.swing.JPanel();
        PanelMain = new javax.swing.JPanel();
        ProjectPanel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        ServicePanel = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        ProductPanel = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        CommunityPanel = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        PanelBody.setBackground(new java.awt.Color(89, 89, 89));

        PanelMenu.setBackground(new java.awt.Color(38, 38, 38));

        jLabel8.setFont(new java.awt.Font("Palatino Linotype", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 190, 127));
        jLabel8.setText("ProSearch");

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(89, 89, 89));
        jLabel6.setText("ProSearch");

        btnProject.setBackground(new java.awt.Color(38, 38, 38));
        btnProject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProjectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProjectMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnProjectMousePressed(evt);
            }
        });
        btnProject.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(89, 89, 89));
        jLabel1.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("PROJECT");
        btnProject.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        IndicatorProject.setBackground(new java.awt.Color(255, 192, 0));

        javax.swing.GroupLayout IndicatorProjectLayout = new javax.swing.GroupLayout(IndicatorProject);
        IndicatorProject.setLayout(IndicatorProjectLayout);
        IndicatorProjectLayout.setHorizontalGroup(
            IndicatorProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        IndicatorProjectLayout.setVerticalGroup(
            IndicatorProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        btnProject.add(IndicatorProject, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, -1));

        btnService.setBackground(new java.awt.Color(38, 38, 38));
        btnService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnServiceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnServiceMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnServiceMousePressed(evt);
            }
        });
        btnService.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(89, 89, 89));
        jLabel2.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("SERVICE");
        btnService.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        IndicatorService.setBackground(new java.awt.Color(255, 192, 0));

        javax.swing.GroupLayout IndicatorServiceLayout = new javax.swing.GroupLayout(IndicatorService);
        IndicatorService.setLayout(IndicatorServiceLayout);
        IndicatorServiceLayout.setHorizontalGroup(
            IndicatorServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        IndicatorServiceLayout.setVerticalGroup(
            IndicatorServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        btnService.add(IndicatorService, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, -1));

        btnProduct.setBackground(new java.awt.Color(38, 38, 38));
        btnProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProductMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProductMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnProductMousePressed(evt);
            }
        });
        btnProduct.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(89, 89, 89));
        jLabel3.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("PRODUCT");
        btnProduct.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        IndicatorProduct.setBackground(new java.awt.Color(255, 192, 0));

        javax.swing.GroupLayout IndicatorProductLayout = new javax.swing.GroupLayout(IndicatorProduct);
        IndicatorProduct.setLayout(IndicatorProductLayout);
        IndicatorProductLayout.setHorizontalGroup(
            IndicatorProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        IndicatorProductLayout.setVerticalGroup(
            IndicatorProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        btnProduct.add(IndicatorProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, -1));

        btnCommunity.setBackground(new java.awt.Color(38, 38, 38));
        btnCommunity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCommunityMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCommunityMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCommunityMousePressed(evt);
            }
        });
        btnCommunity.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(89, 89, 89));
        jLabel4.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("COMMUNITY");
        btnCommunity.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        IndicatorCommunity.setBackground(new java.awt.Color(255, 192, 0));

        javax.swing.GroupLayout IndicatorCommunityLayout = new javax.swing.GroupLayout(IndicatorCommunity);
        IndicatorCommunity.setLayout(IndicatorCommunityLayout);
        IndicatorCommunityLayout.setHorizontalGroup(
            IndicatorCommunityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        IndicatorCommunityLayout.setVerticalGroup(
            IndicatorCommunityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        btnCommunity.add(IndicatorCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, -1));

        javax.swing.GroupLayout PanelMenuLayout = new javax.swing.GroupLayout(PanelMenu);
        PanelMenu.setLayout(PanelMenuLayout);
        PanelMenuLayout.setHorizontalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnService, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCommunity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMenuLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8))
                    .addComponent(jLabel6))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        PanelMenuLayout.setVerticalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addGap(91, 91, 91)
                .addComponent(btnProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelMain.setLayout(new java.awt.CardLayout());

        ProjectPanel.setBackground(new java.awt.Color(242, 242, 242));

        jTabbedPane1.setFont(new java.awt.Font("Montserrat Light", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 793, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Browse Project", jPanel9);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 793, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Create Project", jPanel10);

        javax.swing.GroupLayout ProjectPanelLayout = new javax.swing.GroupLayout(ProjectPanel);
        ProjectPanel.setLayout(ProjectPanelLayout);
        ProjectPanelLayout.setHorizontalGroup(
            ProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        ProjectPanelLayout.setVerticalGroup(
            ProjectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProjectPanelLayout.createSequentialGroup()
                .addGap(0, 139, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PanelMain.add(ProjectPanel, "card5");

        ServicePanel.setBackground(new java.awt.Color(242, 242, 242));

        jTabbedPane2.setFont(new java.awt.Font("Montserrat Light", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 793, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Browse Service", jPanel11);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 793, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Create Service", jPanel12);

        javax.swing.GroupLayout ServicePanelLayout = new javax.swing.GroupLayout(ServicePanel);
        ServicePanel.setLayout(ServicePanelLayout);
        ServicePanelLayout.setHorizontalGroup(
            ServicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        ServicePanelLayout.setVerticalGroup(
            ServicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ServicePanelLayout.createSequentialGroup()
                .addGap(0, 139, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PanelMain.add(ServicePanel, "card4");

        ProductPanel.setBackground(new java.awt.Color(242, 242, 242));

        jTabbedPane3.setFont(new java.awt.Font("Montserrat Light", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 793, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Browse Product", jPanel13);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 793, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Create Product", jPanel14);

        javax.swing.GroupLayout ProductPanelLayout = new javax.swing.GroupLayout(ProductPanel);
        ProductPanel.setLayout(ProductPanelLayout);
        ProductPanelLayout.setHorizontalGroup(
            ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        ProductPanelLayout.setVerticalGroup(
            ProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProductPanelLayout.createSequentialGroup()
                .addGap(0, 139, Short.MAX_VALUE)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PanelMain.add(ProductPanel, "card3");

        CommunityPanel.setBackground(new java.awt.Color(242, 242, 242));

        jTabbedPane4.setFont(new java.awt.Font("Montserrat Light", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 793, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("Browse Community", jPanel15);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 793, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("Create Community", jPanel16);

        javax.swing.GroupLayout CommunityPanelLayout = new javax.swing.GroupLayout(CommunityPanel);
        CommunityPanel.setLayout(CommunityPanelLayout);
        CommunityPanelLayout.setHorizontalGroup(
            CommunityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );
        CommunityPanelLayout.setVerticalGroup(
            CommunityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CommunityPanelLayout.createSequentialGroup()
                .addGap(0, 139, Short.MAX_VALUE)
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PanelMain.add(CommunityPanel, "card2");

        javax.swing.GroupLayout PanelBodyLayout = new javax.swing.GroupLayout(PanelBody);
        PanelBody.setLayout(PanelBodyLayout);
        PanelBodyLayout.setHorizontalGroup(
            PanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBodyLayout.createSequentialGroup()
                .addComponent(PanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelBodyLayout.setVerticalGroup(
            PanelBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProjectMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProjectMousePressed
        // TODO add your handling code here:
        // remove panel
        PanelMain.removeAll();
        PanelMain.repaint();
        PanelMain.revalidate();

        onClick(btnProject);
        onleaveClick(btnService);
        onleaveClick(btnProduct);
        onleaveClick(btnCommunity);
        
        IndicatorProject.setVisible(true);
        IndicatorService.setVisible(false);
        IndicatorProduct.setVisible(false);
        IndicatorCommunity.setVisible(false);
        
        // add panel
        PanelMain.add(ProjectPanel);
        PanelMain.repaint();
        PanelMain.revalidate();
    }//GEN-LAST:event_btnProjectMousePressed

    private void btnServiceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServiceMousePressed
        // TODO add your handling code here:
        // remove panel
        PanelMain.removeAll();
        PanelMain.repaint();
        PanelMain.revalidate();

        onClick(btnService);
        onleaveClick(btnProject);
        onleaveClick(btnProduct);
        onleaveClick(btnCommunity);
        
        IndicatorService.setVisible(true);
        IndicatorProject.setVisible(false);
        IndicatorProduct.setVisible(false);
        IndicatorCommunity.setVisible(false);
        
        // add panel
        PanelMain.add(ServicePanel);
        PanelMain.repaint();
        PanelMain.revalidate();
    }//GEN-LAST:event_btnServiceMousePressed

    private void btnProductMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductMousePressed
        // TODO add your handling code here:
        // remove panel
        PanelMain.removeAll();
        PanelMain.repaint();
        PanelMain.revalidate();

        onClick(btnProduct);
        onleaveClick(btnProject);
        onleaveClick(btnService);
        onleaveClick(btnCommunity);
        
        IndicatorProduct.setVisible(true);
        IndicatorProject.setVisible(false);
        IndicatorService.setVisible(false);
        IndicatorCommunity.setVisible(false);
        
        // add panel
        PanelMain.add(ProductPanel);
        PanelMain.repaint();
        PanelMain.revalidate();
    }//GEN-LAST:event_btnProductMousePressed

    private void btnCommunityMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCommunityMousePressed
        // TODO add your handling code here:
        // remove panel
        PanelMain.removeAll();
        PanelMain.repaint();
        PanelMain.revalidate();

        onClick(btnCommunity);
        onleaveClick(btnProject);
        onleaveClick(btnService);
        onleaveClick(btnProduct);
        
        IndicatorCommunity.setVisible(true);
        IndicatorProject.setVisible(false);
        IndicatorService.setVisible(false);
        IndicatorProduct.setVisible(false);
        
        // add panel
        PanelMain.add(CommunityPanel);
        PanelMain.repaint();
        PanelMain.revalidate();
    }//GEN-LAST:event_btnCommunityMousePressed

    private void btnProjectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProjectMouseEntered
        // TODO add your handling code here:
        onHover(btnProject);
        onLeaveHover(btnService);
        onLeaveHover(btnProduct);
        onLeaveHover(btnCommunity);
    }//GEN-LAST:event_btnProjectMouseEntered

    private void btnServiceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServiceMouseEntered
        // TODO add your handling code here:
        onHover(btnService);
        onLeaveHover(btnProject);
        onLeaveHover(btnProduct);
        onLeaveHover(btnCommunity);
    }//GEN-LAST:event_btnServiceMouseEntered

    private void btnProductMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductMouseEntered
        // TODO add your handling code here:
        onHover(btnProduct);
        onLeaveHover(btnProject);
        onLeaveHover(btnService);
        onLeaveHover(btnCommunity);
    }//GEN-LAST:event_btnProductMouseEntered

    private void btnCommunityMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCommunityMouseEntered
        // TODO add your handling code here:
        onHover(btnCommunity);
        onLeaveHover(btnProject);
        onLeaveHover(btnProduct);
        onLeaveHover(btnService);
    }//GEN-LAST:event_btnCommunityMouseEntered

    private void btnProjectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProjectMouseExited
        // TODO add your handling code here:
        onLeaveHover(btnProject);
    }//GEN-LAST:event_btnProjectMouseExited

    private void btnServiceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServiceMouseExited
        // TODO add your handling code here:
        onLeaveHover(btnService);
    }//GEN-LAST:event_btnServiceMouseExited

    private void btnProductMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductMouseExited
        // TODO add your handling code here:
        onLeaveHover(btnProduct);
    }//GEN-LAST:event_btnProductMouseExited

    private void btnCommunityMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCommunityMouseExited
        // TODO add your handling code here:
        onLeaveHover(btnCommunity);
    }//GEN-LAST:event_btnCommunityMouseExited

    public void onHover(JPanel panel){
        panel.setBackground(new Color(204,204,204));
    }
    
    public void onLeaveHover(JPanel panel){
        panel.setBackground(new Color(38,38,38));
    }
    
    public void onClick(JPanel panel){
        panel.setBackground(new Color(204,204,204));
    }
    
    public void onleaveClick(JPanel panel){
        panel.setBackground(new Color(38,38,38));
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CommunityPanel;
    private javax.swing.JPanel IndicatorCommunity;
    private javax.swing.JPanel IndicatorProduct;
    private javax.swing.JPanel IndicatorProject;
    private javax.swing.JPanel IndicatorService;
    private javax.swing.JPanel PanelBody;
    private javax.swing.JPanel PanelMain;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JPanel ProductPanel;
    private javax.swing.JPanel ProjectPanel;
    private javax.swing.JPanel ServicePanel;
    private javax.swing.JPanel btnCommunity;
    private javax.swing.JPanel btnProduct;
    private javax.swing.JPanel btnProject;
    private javax.swing.JPanel btnService;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    // End of variables declaration//GEN-END:variables
}
