/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerPayment;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;


/**
 *
 * @author Goji
 */
public class PaymentView extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public PaymentView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tfTransId = new javax.swing.JTextField();
        btnFinish = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfTitleProduct = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfPrice = new javax.swing.JTextField();
        cbBank = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        tfNoRek = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(38, 38, 38));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfTransId.setBackground(new java.awt.Color(38, 38, 38));
        tfTransId.setFont(new java.awt.Font("Montserrat Light", 0, 16)); // NOI18N
        tfTransId.setForeground(new java.awt.Color(242, 242, 242));
        tfTransId.setText("TR001");
        tfTransId.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(242, 242, 242)));
        tfTransId.setCaretColor(new java.awt.Color(242, 242, 242));
        tfTransId.setOpaque(false);
        tfTransId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTransIdActionPerformed(evt);
            }
        });
        jPanel1.add(tfTransId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 400, 40));

        btnFinish.setBackground(new java.awt.Color(255, 192, 0));
        btnFinish.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        btnFinish.setText("FINISH");
        btnFinish.setToolTipText("");
        btnFinish.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 192, 0)));
        btnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishActionPerformed(evt);
            }
        });
        jPanel1.add(btnFinish, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 520, 130, 40));

        jLabel6.setFont(new java.awt.Font("Montserrat SemiBold", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 192, 0));
        jLabel6.setText("PAYMENT");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, -1));

        jLabel7.setFont(new java.awt.Font("Palatino Linotype", 1, 100)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 190, 127));
        jLabel7.setText("ProSearch");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 1, 100)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(89, 89, 89));
        jLabel5.setText("ProSearch");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jLabel10.setBackground(new java.awt.Color(153, 153, 153));
        jLabel10.setFont(new java.awt.Font("Montserrat Light", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("TRANSACTION ID");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, 20));

        jLabel11.setFont(new java.awt.Font("Montserrat Light", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("TITLE");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, 20));

        tfTitleProduct.setBackground(new java.awt.Color(38, 38, 38));
        tfTitleProduct.setFont(new java.awt.Font("Montserrat Light", 0, 16)); // NOI18N
        tfTitleProduct.setForeground(new java.awt.Color(242, 242, 242));
        tfTitleProduct.setText("[Dicari] Penulis ");
        tfTitleProduct.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(242, 242, 242)));
        tfTitleProduct.setCaretColor(new java.awt.Color(242, 242, 242));
        tfTitleProduct.setOpaque(false);
        tfTitleProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTitleProductActionPerformed(evt);
            }
        });
        jPanel1.add(tfTitleProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 400, 40));

        jLabel13.setFont(new java.awt.Font("Montserrat Light", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("BANK");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, -1, 20));

        jLabel14.setFont(new java.awt.Font("Montserrat Light", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText("PRICE");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, 20));

        tfPrice.setBackground(new java.awt.Color(38, 38, 38));
        tfPrice.setFont(new java.awt.Font("Montserrat Light", 0, 16)); // NOI18N
        tfPrice.setForeground(new java.awt.Color(242, 242, 242));
        tfPrice.setText("500000");
        tfPrice.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(242, 242, 242)));
        tfPrice.setCaretColor(new java.awt.Color(242, 242, 242));
        tfPrice.setOpaque(false);
        tfPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPriceActionPerformed(evt);
            }
        });
        jPanel1.add(tfPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 400, 40));

        cbBank.setFont(new java.awt.Font("Montserrat Light", 0, 16)); // NOI18N
        cbBank.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BNI", "Mandiri", "BCA", "BRI" }));
        cbBank.setOpaque(false);
        jPanel1.add(cbBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 130, 30));

        jLabel15.setFont(new java.awt.Font("Montserrat Light", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("NO. REK");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, -1, 20));

        tfNoRek.setEditable(false);
        tfNoRek.setBackground(new java.awt.Color(38, 38, 38));
        tfNoRek.setFont(new java.awt.Font("Montserrat Light", 0, 16)); // NOI18N
        tfNoRek.setForeground(new java.awt.Color(242, 242, 242));
        tfNoRek.setText("0700-000-899-992");
        tfNoRek.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(242, 242, 242)));
        tfNoRek.setCaretColor(new java.awt.Color(242, 242, 242));
        tfNoRek.setOpaque(false);
        tfNoRek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNoRekActionPerformed(evt);
            }
        });
        jPanel1.add(tfNoRek, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 370, 400, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1098, 637));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfTitleProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTitleProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTitleProductActionPerformed

    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinishActionPerformed

    private void tfTransIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTransIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTransIdActionPerformed

    private void tfPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPriceActionPerformed

    private void tfNoRekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNoRekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNoRekActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinish;
    private javax.swing.JComboBox<String> cbBank;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfNoRek;
    private javax.swing.JTextField tfPrice;
    private javax.swing.JTextField tfTitleProduct;
    private javax.swing.JTextField tfTransId;
    // End of variables declaration//GEN-END:variables

    
    public String getCbBank() {
        return cbBank.getSelectedItem().toString();
    }

    public void setTfPrice(String x) {
        tfPrice.setText(x);
    }

    public void setTfTitleProduct(String x) {
        tfTitleProduct.setText(x);
    }

    public void setTfTransId(String x) {
        tfTransId.setText(x);
    }

    public JButton getBtnFinish() {
        return btnFinish;
    }
    
    public void addActionListener(ActionListener x){
        btnFinish.addActionListener(x);
    }

    
    
    
}
